name: PlatformIO CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      REF: ${{ github.ref_name }}

    steps:
    - name: Check out source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Build pico env
      run: |
        pio run -e pico
        mkdir -p pico
        cp .pio/build/pico/firmware.uf2  pico/HayBox-${{ env.REF }}-pico.uf2

    - name: Publish pico artifacts
      uses: actions/upload-artifact@v3
      with:
        name: HayBox-${{ env.REF }}-pico.uf2
        path: pico/HayBox-${{ env.REF }}-pico.uf2

    - name: Upload binaries to release
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        files: pico/HayBox-${{ env.REF }}-pico.uf2
